title: Dark MS Theme
description: A simple GitHub Pages theme with Microsoft fonts & colours

# Header buttons for downloads and link to GitHub repo 
#show_downloads: false
#hide_github: true

# Can specify PNG favicon
favicon: https://webiconspng.com/wp-content/uploads/2017/09/Microsoft-PNG-Image-83610.png

# Theme supports custom buttons
buttons:
  - text: Test Header Button
    href: http://example.net

# Icon shown in header. From Fontawesome https://fontawesome.com/icons?m=free
icon: fas fa-pencil-alt

# Colour gradient for the header
header-colours: 
  - #8a108c
  - #cc580c
